
// Generated by Cadence Genus(TM) Synthesis Solution 17.10-p007_1
// Generated on: Dec  9 2018 19:06:27 EST (Dec 10 2018 00:06:27 UTC)

// Verification Directory fv/rv_pc 

module add_unsigned_62(A, B, Z);
  input [31:0] A;
  input [2:0] B;
  output [31:0] Z;
  wire [31:0] A;
  wire [2:0] B;
  wire [31:0] Z;
  wire n_77, n_242, n_243, n_247, n_251, n_299, n_300, n_304;
  wire n_306, n_309, n_312, n_315, n_318, n_357, n_358, n_362;
  wire n_364, n_367, n_370, n_373, n_374, n_378, n_382, n_386;
  wire n_390, n_394, n_398, n_402, n_516, n_517, n_518, n_519;
  wire n_520, n_521, n_522, n_523, n_524, n_525, n_526, n_527;
  wire n_528, n_529, n_530, n_531, n_532, n_533, n_534, n_535;
  wire n_536, n_537, n_538, n_539, n_540, n_541, n_542, n_543;
  wire n_544, n_545, n_546, n_547, n_548, n_549, n_550, n_551;
  wire n_552, n_553, n_554, n_555, n_556, n_557, n_558, n_559;
  wire n_560, n_561, n_562, n_563, n_564, n_565, n_566, n_567;
  wire n_568, n_569, n_570, n_571, n_572, n_573;
  assign Z[0] = 1'b0;
  assign Z[1] = 1'b0;
  assign Z[2] = 1'b0;
  or g540 (n_299, wc, n_251);
  not gc (wc, A[8]);
  or g550 (n_357, wc0, n_318);
  not gc0 (wc0, A[16]);
  or g621 (n_402, n_398, wc1);
  not gc1 (wc1, A[30]);
  or g626 (n_394, n_390, wc2);
  not gc2 (wc2, A[28]);
  or g629 (n_386, n_382, wc3);
  not gc3 (wc3, A[26]);
  or g632 (n_378, n_374, wc4);
  not gc4 (wc4, A[24]);
  or g633 (n_373, n_370, wc5);
  not gc5 (wc5, A[22]);
  or g635 (n_367, n_364, wc6);
  not gc6 (wc6, A[20]);
  or g636 (n_362, n_358, wc7);
  not gc7 (wc7, A[18]);
  or g637 (n_315, n_312, wc8);
  not gc8 (wc8, A[14]);
  or g639 (n_309, n_306, wc9);
  not gc9 (wc9, A[12]);
  or g640 (n_304, n_300, wc10);
  not gc10 (wc10, A[10]);
  or g643 (n_318, n_315, wc11);
  not gc11 (wc11, A[15]);
  or g644 (n_247, n_243, wc12);
  not gc12 (wc12, A[6]);
  or g646 (n_251, n_247, wc13);
  not gc13 (wc13, A[7]);
  or g656 (n_398, n_394, wc14);
  not gc14 (wc14, A[29]);
  or g657 (n_382, n_378, wc15);
  not gc15 (wc15, A[25]);
  or g658 (n_358, n_357, wc16);
  not gc16 (wc16, A[17]);
  or g659 (n_300, n_299, wc17);
  not gc17 (wc17, A[9]);
  or g660 (n_312, n_309, wc18);
  not gc18 (wc18, A[13]);
  or g661 (n_243, n_242, wc19);
  not gc19 (wc19, A[5]);
  or g669 (n_390, n_386, wc20);
  not gc20 (wc20, A[27]);
  or g672 (n_374, n_373, wc21);
  not gc21 (wc21, A[23]);
  or g675 (n_306, n_304, wc22);
  not gc22 (wc22, A[11]);
  or g678 (n_370, n_367, wc23);
  not gc23 (wc23, A[21]);
  or g681 (n_364, n_362, wc24);
  not gc24 (wc24, A[19]);
  nand g682 (n_516, n_402, A[31]);
  or g683 (n_517, n_402, A[31]);
  nand g684 (Z[31], n_516, n_517);
  nand g685 (n_518, n_398, A[30]);
  or g686 (n_519, n_398, A[30]);
  nand g687 (Z[30], n_518, n_519);
  nand g688 (n_520, n_394, A[29]);
  or g689 (n_521, n_394, A[29]);
  nand g690 (Z[29], n_520, n_521);
  nand g691 (n_522, n_390, A[28]);
  or g692 (n_523, n_390, A[28]);
  nand g693 (Z[28], n_522, n_523);
  nand g694 (n_524, n_386, A[27]);
  or g695 (n_525, n_386, A[27]);
  nand g696 (Z[27], n_524, n_525);
  nand g697 (n_526, n_382, A[26]);
  or g698 (n_527, n_382, A[26]);
  nand g699 (Z[26], n_526, n_527);
  nand g700 (n_528, n_378, A[25]);
  or g701 (n_529, n_378, A[25]);
  nand g702 (Z[25], n_528, n_529);
  nand g703 (n_530, n_374, A[24]);
  or g704 (n_531, n_374, A[24]);
  nand g705 (Z[24], n_530, n_531);
  nand g706 (n_532, n_373, A[23]);
  or g707 (n_533, n_373, A[23]);
  nand g708 (Z[23], n_532, n_533);
  nand g709 (n_534, n_370, A[22]);
  or g710 (n_535, n_370, A[22]);
  nand g711 (Z[22], n_534, n_535);
  nand g712 (n_536, n_367, A[21]);
  or g713 (n_537, n_367, A[21]);
  nand g714 (Z[21], n_536, n_537);
  nand g715 (n_538, n_364, A[20]);
  or g716 (n_539, n_364, A[20]);
  nand g717 (Z[20], n_538, n_539);
  nand g718 (n_540, n_362, A[19]);
  or g719 (n_541, n_362, A[19]);
  nand g720 (Z[19], n_540, n_541);
  nand g721 (n_542, n_358, A[18]);
  or g722 (n_543, n_358, A[18]);
  nand g723 (Z[18], n_542, n_543);
  nand g724 (n_544, n_357, A[17]);
  or g725 (n_545, n_357, A[17]);
  nand g726 (Z[17], n_544, n_545);
  nand g727 (n_546, n_318, A[16]);
  or g728 (n_547, n_318, A[16]);
  nand g729 (Z[16], n_546, n_547);
  nand g730 (n_548, n_315, A[15]);
  or g731 (n_549, n_315, A[15]);
  nand g732 (Z[15], n_548, n_549);
  nand g733 (n_550, n_312, A[14]);
  or g734 (n_551, n_312, A[14]);
  nand g735 (Z[14], n_550, n_551);
  nand g736 (n_552, n_309, A[13]);
  or g737 (n_553, n_309, A[13]);
  nand g738 (Z[13], n_552, n_553);
  nand g739 (n_554, n_306, A[12]);
  or g740 (n_555, n_306, A[12]);
  nand g741 (Z[12], n_554, n_555);
  nand g742 (n_556, n_304, A[11]);
  or g743 (n_557, n_304, A[11]);
  nand g744 (Z[11], n_556, n_557);
  nand g745 (n_558, n_300, A[10]);
  or g746 (n_559, n_300, A[10]);
  nand g747 (Z[10], n_558, n_559);
  nand g748 (n_560, n_299, A[9]);
  or g749 (n_561, n_299, A[9]);
  nand g750 (Z[9], n_560, n_561);
  nand g751 (n_562, n_251, A[8]);
  or g752 (n_563, n_251, A[8]);
  nand g753 (Z[8], n_562, n_563);
  nand g754 (n_564, n_247, A[7]);
  or g755 (n_565, n_247, A[7]);
  nand g756 (Z[7], n_564, n_565);
  nand g757 (n_566, n_243, A[6]);
  or g758 (n_567, n_243, A[6]);
  nand g759 (Z[6], n_566, n_567);
  nand g760 (n_568, n_242, A[5]);
  or g761 (n_569, n_242, A[5]);
  nand g762 (Z[5], n_568, n_569);
  or g763 (n_570, n_77, A[4]);
  nand g764 (n_571, n_77, A[4]);
  nand g765 (Z[4], n_570, n_571);
  or g766 (n_242, n_77, wc25);
  not gc25 (wc25, A[4]);
  or g767 (n_572, wc26, A[2]);
  not gc26 (wc26, A[3]);
  or g768 (n_573, A[3], wc27);
  not gc27 (wc27, A[2]);
  nand g769 (Z[3], n_572, n_573);
  nand g770 (n_77, A[3], A[2]);
endmodule

module rv_pc(in_clk, in_rstn, in_stall, in_transfert, in_target,
     out_pc);
  input in_clk, in_rstn, in_stall, in_transfert;
  input [31:0] in_target;
  output [31:0] out_pc;
  wire in_clk, in_rstn, in_stall, in_transfert;
  wire [31:0] in_target;
  wire [31:0] out_pc;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_164, n_165, n_166,
       n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_229, n_230, n_231, n_232, n_233, n_234, n_235, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_252;
  wire n_253, n_254, n_255, n_256, n_257, n_258, n_259, n_260;
  wire n_261, n_263, n_264, n_484, n_485, n_486, n_487, n_496;
  wire n_497, n_498, n_499, n_508, n_509, n_510, n_511, n_520;
  wire n_521, n_522, n_523, n_532, n_533, n_534, n_535, n_544;
  wire n_545, n_546, n_547, n_556, n_557, n_558, n_559, n_568;
  wire n_569, n_570, n_571, n_580, n_581, n_582, n_583, n_592;
  wire n_593, n_594, n_595, n_604, n_605, n_606, n_607, n_616;
  wire n_617, n_618, n_619, n_628, n_629, n_630, n_631, n_640;
  wire n_641, n_642, n_643, n_652, n_653, n_654, n_655, n_664;
  wire n_665, n_666, n_667, n_676, n_677, n_678, n_679, n_688;
  wire n_689, n_690, n_691, n_700, n_701, n_702, n_703, n_712;
  wire n_713, n_714, n_715, n_724, n_725, n_726, n_727, n_736;
  wire n_737, n_738, n_739, n_748, n_749, n_750, n_751, n_760;
  wire n_761, n_762, n_763, n_772, n_773, n_774, n_775, n_784;
  wire n_785, n_786, n_787, n_796, n_797, n_798, n_799, n_808;
  wire n_809, n_810, n_811, n_820, n_821, n_822, n_823, n_832;
  wire n_833, n_834, n_835, n_840, n_841, n_846, n_847;
  add_unsigned_62 add_29_43(.A ({out_pc[31:2], 2'b00}), .B (3'b100), .Z
       ({n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172,
       n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181,
       n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190,
       n_191, n_192, UNCONNECTED1, UNCONNECTED0, UNCONNECTED}));
  not g39 (n_229, in_rstn);
  or g476 (n_250, wc28, n_703);
  not gc28 (wc28, n_702);
  or g477 (n_241, wc29, n_595);
  not gc29 (wc29, n_594);
  or g478 (n_232, wc30, n_487);
  not gc30 (wc30, n_486);
  or g479 (n_256, wc31, n_775);
  not gc31 (wc31, n_774);
  or g480 (n_253, wc32, n_739);
  not gc32 (wc32, n_738);
  or g481 (n_233, wc33, n_499);
  not gc33 (wc33, n_498);
  or g482 (n_248, wc34, n_679);
  not gc34 (wc34, n_678);
  or g483 (n_261, wc35, n_835);
  not gc35 (wc35, n_834);
  or g484 (n_242, wc36, n_607);
  not gc36 (wc36, n_606);
  or g485 (n_234, wc37, n_511);
  not gc37 (wc37, n_510);
  or g486 (n_246, wc38, n_655);
  not gc38 (wc38, n_654);
  or g487 (n_235, wc39, n_523);
  not gc39 (wc39, n_522);
  or g488 (n_260, wc40, n_823);
  not gc40 (wc40, n_822);
  or g489 (n_255, wc41, n_763);
  not gc41 (wc41, n_762);
  or g490 (n_249, wc42, n_691);
  not gc42 (wc42, n_690);
  or g491 (n_236, wc43, n_535);
  not gc43 (wc43, n_534);
  or g492 (n_243, wc44, n_619);
  not gc44 (wc44, n_618);
  or g493 (n_259, wc45, n_811);
  not gc45 (wc45, n_810);
  or g494 (n_247, wc46, n_667);
  not gc46 (wc46, n_666);
  or g495 (n_237, wc47, n_547);
  not gc47 (wc47, n_546);
  or g496 (n_244, wc48, n_631);
  not gc48 (wc48, n_630);
  or g497 (n_238, wc49, n_559);
  not gc49 (wc49, n_558);
  or g498 (n_258, wc50, n_799);
  not gc50 (wc50, n_798);
  or g499 (n_254, wc51, n_751);
  not gc51 (wc51, n_750);
  or g500 (n_252, wc52, n_727);
  not gc52 (wc52, n_726);
  or g501 (n_239, wc53, n_571);
  not gc53 (wc53, n_570);
  or g502 (n_251, wc54, n_715);
  not gc54 (wc54, n_714);
  or g503 (n_257, wc55, n_787);
  not gc55 (wc55, n_786);
  or g504 (n_245, wc56, n_643);
  not gc56 (wc56, n_642);
  or g505 (n_240, wc57, n_583);
  not gc57 (wc57, n_582);
  nand g506 (n_487, n_484, n_485);
  nand g507 (n_230, n_846, n_847);
  nand g508 (n_499, n_496, n_497);
  nand g509 (n_231, n_840, n_841);
  nand g510 (n_511, n_508, n_509);
  nand g511 (n_835, n_832, n_833);
  nand g512 (n_523, n_520, n_521);
  nand g513 (n_823, n_820, n_821);
  nand g514 (n_535, n_532, n_533);
  nand g515 (n_547, n_544, n_545);
  nand g516 (n_811, n_808, n_809);
  nand g517 (n_559, n_556, n_557);
  nand g518 (n_799, n_796, n_797);
  nand g519 (n_571, n_568, n_569);
  nand g520 (n_583, n_580, n_581);
  nand g521 (n_703, n_700, n_701);
  nand g522 (n_595, n_592, n_593);
  nand g523 (n_775, n_772, n_773);
  nand g524 (n_607, n_604, n_605);
  nand g525 (n_619, n_616, n_617);
  nand g526 (n_763, n_760, n_761);
  nand g527 (n_631, n_628, n_629);
  nand g528 (n_751, n_748, n_749);
  nand g529 (n_643, n_640, n_641);
  nand g530 (n_655, n_652, n_653);
  nand g531 (n_739, n_736, n_737);
  nand g532 (n_667, n_664, n_665);
  nand g533 (n_727, n_724, n_725);
  nand g534 (n_679, n_676, n_677);
  nand g535 (n_691, n_688, n_689);
  nand g536 (n_715, n_712, n_713);
  nand g537 (n_787, n_784, n_785);
  or g538 (n_809, n_263, wc58);
  not gc58 (wc58, n_166);
  or g539 (n_702, n_264, wc59);
  not gc59 (wc59, in_target[20]);
  or g540 (n_701, n_263, wc60);
  not gc60 (wc60, n_175);
  or g541 (n_810, n_264, wc61);
  not gc61 (wc61, in_target[29]);
  or g542 (n_713, n_263, wc62);
  not gc62 (wc62, n_174);
  or g543 (n_714, n_264, wc63);
  not gc63 (wc63, in_target[21]);
  or g544 (n_690, n_264, wc64);
  not gc64 (wc64, in_target[19]);
  or g545 (n_689, n_263, wc65);
  not gc65 (wc65, n_176);
  or g546 (n_546, n_264, wc66);
  not gc66 (wc66, in_target[7]);
  or g547 (n_545, n_263, wc67);
  not gc67 (wc67, n_188);
  or g548 (n_725, n_263, wc68);
  not gc68 (wc68, n_173);
  or g549 (n_678, n_264, wc69);
  not gc69 (wc69, in_target[18]);
  or g550 (n_677, n_263, wc70);
  not gc70 (wc70, n_177);
  or g551 (n_497, n_263, wc71);
  not gc71 (wc71, n_192);
  or g552 (n_726, n_264, wc72);
  not gc72 (wc72, in_target[22]);
  or g553 (n_484, n_263, out_pc[2]);
  or g554 (n_666, n_264, wc73);
  not gc73 (wc73, in_target[17]);
  or g555 (n_821, n_263, wc74);
  not gc74 (wc74, n_165);
  or g556 (n_534, n_264, wc75);
  not gc75 (wc75, in_target[6]);
  or g557 (n_737, n_263, wc76);
  not gc76 (wc76, n_172);
  or g558 (n_738, n_264, wc77);
  not gc77 (wc77, in_target[23]);
  or g559 (n_654, n_264, wc78);
  not gc78 (wc78, in_target[16]);
  or g560 (n_653, n_263, wc79);
  not gc79 (wc79, n_179);
  or g561 (n_533, n_263, wc80);
  not gc80 (wc80, n_189);
  or g562 (n_847, n_264, wc81);
  not gc81 (wc81, in_target[0]);
  or g563 (n_749, n_263, wc82);
  not gc82 (wc82, n_171);
  or g564 (n_642, n_264, wc83);
  not gc83 (wc83, in_target[15]);
  or g565 (n_641, n_263, wc84);
  not gc84 (wc84, n_180);
  or g566 (n_822, n_264, wc85);
  not gc85 (wc85, in_target[30]);
  or g567 (n_750, n_264, wc86);
  not gc86 (wc86, in_target[24]);
  nand g568 (n_846, n_264, out_pc[0]);
  or g569 (n_630, n_264, wc87);
  not gc87 (wc87, in_target[14]);
  or g570 (n_629, n_263, wc88);
  not gc88 (wc88, n_181);
  or g571 (n_522, n_264, wc89);
  not gc89 (wc89, in_target[5]);
  or g572 (n_761, n_263, wc90);
  not gc90 (wc90, n_170);
  or g573 (n_762, n_264, wc91);
  not gc91 (wc91, in_target[25]);
  or g574 (n_618, n_264, wc92);
  not gc92 (wc92, in_target[13]);
  or g575 (n_617, n_263, wc93);
  not gc93 (wc93, n_182);
  or g576 (n_521, n_263, wc94);
  not gc94 (wc94, n_190);
  or g577 (n_665, n_263, wc95);
  not gc95 (wc95, n_178);
  or g578 (n_773, n_263, wc96);
  not gc96 (wc96, n_169);
  or g579 (n_606, n_264, wc97);
  not gc97 (wc97, in_target[12]);
  or g580 (n_605, n_263, wc98);
  not gc98 (wc98, n_183);
  or g581 (n_833, n_263, wc99);
  not gc99 (wc99, n_164);
  or g582 (n_774, n_264, wc100);
  not gc100 (wc100, in_target[26]);
  or g583 (n_834, n_264, wc101);
  not gc101 (wc101, in_target[31]);
  or g584 (n_594, n_264, wc102);
  not gc102 (wc102, in_target[11]);
  or g585 (n_593, n_263, wc103);
  not gc103 (wc103, n_184);
  or g586 (n_510, n_264, wc104);
  not gc104 (wc104, in_target[4]);
  or g587 (n_785, n_263, wc105);
  not gc105 (wc105, n_168);
  or g588 (n_786, n_264, wc106);
  not gc106 (wc106, in_target[27]);
  or g589 (n_582, n_264, wc107);
  not gc107 (wc107, in_target[10]);
  or g590 (n_581, n_263, wc108);
  not gc108 (wc108, n_185);
  or g591 (n_509, n_263, wc109);
  not gc109 (wc109, n_191);
  or g592 (n_485, n_264, wc110);
  not gc110 (wc110, in_target[2]);
  or g593 (n_797, n_263, wc111);
  not gc111 (wc111, n_167);
  or g594 (n_570, n_264, wc112);
  not gc112 (wc112, in_target[9]);
  or g595 (n_569, n_263, wc113);
  not gc113 (wc113, n_186);
  or g596 (n_841, n_264, wc114);
  not gc114 (wc114, in_target[1]);
  or g597 (n_798, n_264, wc115);
  not gc115 (wc115, in_target[28]);
  nand g598 (n_840, n_264, out_pc[1]);
  or g599 (n_558, n_264, wc116);
  not gc116 (wc116, in_target[8]);
  or g600 (n_557, n_263, wc117);
  not gc117 (wc117, n_187);
  or g601 (n_498, n_264, wc118);
  not gc118 (wc118, in_target[3]);
  nand g602 (n_712, out_pc[21], in_stall);
  nand g603 (n_700, out_pc[20], in_stall);
  nand g604 (n_688, out_pc[19], in_stall);
  nand g605 (n_724, out_pc[22], in_stall);
  nand g606 (n_676, out_pc[18], in_stall);
  nand g607 (n_736, out_pc[23], in_stall);
  nand g608 (n_664, out_pc[17], in_stall);
  nand g609 (n_652, out_pc[16], in_stall);
  nand g610 (n_748, out_pc[24], in_stall);
  nand g611 (n_640, out_pc[15], in_stall);
  nand g612 (n_760, out_pc[25], in_stall);
  nand g613 (n_628, out_pc[14], in_stall);
  nand g614 (n_616, out_pc[13], in_stall);
  nand g615 (n_772, out_pc[26], in_stall);
  nand g616 (n_604, out_pc[12], in_stall);
  or g617 (n_263, in_stall, in_transfert);
  nand g618 (n_592, out_pc[11], in_stall);
  nand g619 (n_580, out_pc[10], in_stall);
  nand g620 (n_796, out_pc[28], in_stall);
  nand g621 (n_568, out_pc[9], in_stall);
  nand g622 (n_808, out_pc[29], in_stall);
  nand g623 (n_556, out_pc[8], in_stall);
  nand g624 (n_544, out_pc[7], in_stall);
  nand g625 (n_820, out_pc[30], in_stall);
  nand g626 (n_532, out_pc[6], in_stall);
  nand g627 (n_832, out_pc[31], in_stall);
  nand g628 (n_520, out_pc[5], in_stall);
  nand g629 (n_508, out_pc[4], in_stall);
  nand g630 (n_496, out_pc[3], in_stall);
  nand g631 (n_486, out_pc[2], in_stall);
  or g632 (n_264, in_stall, wc119);
  not gc119 (wc119, in_transfert);
  nand g633 (n_784, out_pc[27], in_stall);
  CDN_flop \pc_reg[0] (.clk (in_clk), .d (n_230), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out_pc[0]));
  CDN_flop \pc_reg[1] (.clk (in_clk), .d (n_231), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out_pc[1]));
  CDN_flop \pc_reg[2] (.clk (in_clk), .d (n_232), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out_pc[2]));
  CDN_flop \pc_reg[3] (.clk (in_clk), .d (n_233), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out_pc[3]));
  CDN_flop \pc_reg[4] (.clk (in_clk), .d (n_234), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out_pc[4]));
  CDN_flop \pc_reg[5] (.clk (in_clk), .d (n_235), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out_pc[5]));
  CDN_flop \pc_reg[6] (.clk (in_clk), .d (n_236), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out_pc[6]));
  CDN_flop \pc_reg[7] (.clk (in_clk), .d (n_237), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out_pc[7]));
  CDN_flop \pc_reg[8] (.clk (in_clk), .d (n_238), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out_pc[8]));
  CDN_flop \pc_reg[9] (.clk (in_clk), .d (n_239), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out_pc[9]));
  CDN_flop \pc_reg[10] (.clk (in_clk), .d (n_240), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[10]));
  CDN_flop \pc_reg[11] (.clk (in_clk), .d (n_241), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[11]));
  CDN_flop \pc_reg[12] (.clk (in_clk), .d (n_242), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[12]));
  CDN_flop \pc_reg[13] (.clk (in_clk), .d (n_243), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[13]));
  CDN_flop \pc_reg[14] (.clk (in_clk), .d (n_244), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[14]));
  CDN_flop \pc_reg[15] (.clk (in_clk), .d (n_245), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[15]));
  CDN_flop \pc_reg[16] (.clk (in_clk), .d (n_246), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[16]));
  CDN_flop \pc_reg[17] (.clk (in_clk), .d (n_247), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[17]));
  CDN_flop \pc_reg[18] (.clk (in_clk), .d (n_248), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[18]));
  CDN_flop \pc_reg[19] (.clk (in_clk), .d (n_249), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[19]));
  CDN_flop \pc_reg[20] (.clk (in_clk), .d (n_250), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[20]));
  CDN_flop \pc_reg[21] (.clk (in_clk), .d (n_251), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[21]));
  CDN_flop \pc_reg[22] (.clk (in_clk), .d (n_252), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[22]));
  CDN_flop \pc_reg[23] (.clk (in_clk), .d (n_253), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[23]));
  CDN_flop \pc_reg[24] (.clk (in_clk), .d (n_254), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[24]));
  CDN_flop \pc_reg[25] (.clk (in_clk), .d (n_255), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[25]));
  CDN_flop \pc_reg[26] (.clk (in_clk), .d (n_256), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[26]));
  CDN_flop \pc_reg[27] (.clk (in_clk), .d (n_257), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[27]));
  CDN_flop \pc_reg[28] (.clk (in_clk), .d (n_258), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[28]));
  CDN_flop \pc_reg[29] (.clk (in_clk), .d (n_259), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[29]));
  CDN_flop \pc_reg[30] (.clk (in_clk), .d (n_260), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[30]));
  CDN_flop \pc_reg[31] (.clk (in_clk), .d (n_261), .sena (1'b1), .aclr
       (n_229), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (out_pc[31]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
