
// Generated by Cadence Genus(TM) Synthesis Solution 17.10-p007_1
// Generated on: Dec  9 2018 19:06:29 EST (Dec 10 2018 00:06:29 UTC)

// Verification Directory fv/rv_pc 

module rv_pc(in_clk, in_rstn, in_stall, in_transfert, in_target,
     out_pc);
  input in_clk, in_rstn, in_stall, in_transfert;
  input [31:0] in_target;
  output [31:0] out_pc;
  wire in_clk, in_rstn, in_stall, in_transfert;
  wire [31:0] in_target;
  wire [31:0] out_pc;
  wire add_29_43_n_1, add_29_43_n_3, add_29_43_n_5, add_29_43_n_7,
       add_29_43_n_9, add_29_43_n_11, add_29_43_n_13, add_29_43_n_15;
  wire add_29_43_n_17, add_29_43_n_19, add_29_43_n_21, add_29_43_n_23,
       add_29_43_n_25, add_29_43_n_27, add_29_43_n_29, add_29_43_n_31;
  wire add_29_43_n_33, add_29_43_n_35, add_29_43_n_37, add_29_43_n_39,
       add_29_43_n_41, add_29_43_n_43, add_29_43_n_45, add_29_43_n_47;
  wire add_29_43_n_49, add_29_43_n_51, add_29_43_n_53, add_29_43_n_55,
       n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95;
  SDFFRHQX1 \pc_reg[0] (.RN (in_rstn), .CK (in_clk), .D (in_target[0]),
       .SI (out_pc[0]), .SE (n_4), .Q (out_pc[0]));
  SDFFRHQX1 \pc_reg[1] (.RN (in_rstn), .CK (in_clk), .D (in_target[1]),
       .SI (out_pc[1]), .SE (n_4), .Q (out_pc[1]));
  DFFRHQX1 \pc_reg[2] (.RN (in_rstn), .CK (in_clk), .D (n_65), .Q
       (out_pc[2]));
  DFFRHQX1 \pc_reg[3] (.RN (in_rstn), .CK (in_clk), .D (n_41), .Q
       (out_pc[3]));
  DFFRHQX1 \pc_reg[4] (.RN (in_rstn), .CK (in_clk), .D (n_37), .Q
       (out_pc[4]));
  DFFRHQX1 \pc_reg[5] (.RN (in_rstn), .CK (in_clk), .D (n_58), .Q
       (out_pc[5]));
  DFFRHQX1 \pc_reg[6] (.RN (in_rstn), .CK (in_clk), .D (n_56), .Q
       (out_pc[6]));
  DFFRHQX1 \pc_reg[7] (.RN (in_rstn), .CK (in_clk), .D (n_55), .Q
       (out_pc[7]));
  DFFRHQX1 \pc_reg[8] (.RN (in_rstn), .CK (in_clk), .D (n_53), .Q
       (out_pc[8]));
  DFFRHQX1 \pc_reg[9] (.RN (in_rstn), .CK (in_clk), .D (n_52), .Q
       (out_pc[9]));
  DFFRHQX1 \pc_reg[10] (.RN (in_rstn), .CK (in_clk), .D (n_63), .Q
       (out_pc[10]));
  DFFRHQX1 \pc_reg[11] (.RN (in_rstn), .CK (in_clk), .D (n_51), .Q
       (out_pc[11]));
  DFFRHQX1 \pc_reg[12] (.RN (in_rstn), .CK (in_clk), .D (n_64), .Q
       (out_pc[12]));
  DFFRHQX1 \pc_reg[13] (.RN (in_rstn), .CK (in_clk), .D (n_35), .Q
       (out_pc[13]));
  DFFRHQX1 \pc_reg[14] (.RN (in_rstn), .CK (in_clk), .D (n_49), .Q
       (out_pc[14]));
  DFFRHQX1 \pc_reg[15] (.RN (in_rstn), .CK (in_clk), .D (n_48), .Q
       (out_pc[15]));
  DFFRHQX1 \pc_reg[16] (.RN (in_rstn), .CK (in_clk), .D (n_47), .Q
       (out_pc[16]));
  DFFRHQX1 \pc_reg[17] (.RN (in_rstn), .CK (in_clk), .D (n_46), .Q
       (out_pc[17]));
  DFFRHQX1 \pc_reg[18] (.RN (in_rstn), .CK (in_clk), .D (n_45), .Q
       (out_pc[18]));
  DFFRHQX1 \pc_reg[19] (.RN (in_rstn), .CK (in_clk), .D (n_44), .Q
       (out_pc[19]));
  DFFRHQX1 \pc_reg[20] (.RN (in_rstn), .CK (in_clk), .D (n_43), .Q
       (out_pc[20]));
  DFFRHQX1 \pc_reg[21] (.RN (in_rstn), .CK (in_clk), .D (n_42), .Q
       (out_pc[21]));
  DFFRHQX1 \pc_reg[22] (.RN (in_rstn), .CK (in_clk), .D (n_40), .Q
       (out_pc[22]));
  DFFRHQX1 \pc_reg[23] (.RN (in_rstn), .CK (in_clk), .D (n_39), .Q
       (out_pc[23]));
  DFFRHQX1 \pc_reg[24] (.RN (in_rstn), .CK (in_clk), .D (n_38), .Q
       (out_pc[24]));
  DFFRHQX1 \pc_reg[25] (.RN (in_rstn), .CK (in_clk), .D (n_36), .Q
       (out_pc[25]));
  DFFRHQX1 \pc_reg[26] (.RN (in_rstn), .CK (in_clk), .D (n_62), .Q
       (out_pc[26]));
  DFFRHQX1 \pc_reg[27] (.RN (in_rstn), .CK (in_clk), .D (n_61), .Q
       (out_pc[27]));
  DFFRHQX1 \pc_reg[28] (.RN (in_rstn), .CK (in_clk), .D (n_60), .Q
       (out_pc[28]));
  DFFRHQX1 \pc_reg[29] (.RN (in_rstn), .CK (in_clk), .D (n_59), .Q
       (out_pc[29]));
  DFFRHQX1 \pc_reg[30] (.RN (in_rstn), .CK (in_clk), .D (n_57), .Q
       (out_pc[30]));
  DFFRHQX1 \pc_reg[31] (.RN (in_rstn), .CK (in_clk), .D (n_54), .Q
       (out_pc[31]));
  OAI2BB1X1 g1641__7837(.A0N (in_stall), .A1N (out_pc[2]), .B0 (n_50),
       .Y (n_65));
  OAI2BB1X1 g1656__7557(.A0N (in_target[12]), .A1N (n_3), .B0 (n_34),
       .Y (n_64));
  OAI2BB1X1 g1657__7654(.A0N (in_target[10]), .A1N (n_3), .B0 (n_23),
       .Y (n_63));
  OAI2BB1X1 g1658__8867(.A0N (n_2), .A1N (n_90), .B0 (n_21), .Y (n_62));
  OAI2BB1X1 g1659__1377(.A0N (n_2), .A1N (n_91), .B0 (n_32), .Y (n_61));
  OAI2BB1X1 g1660__3717(.A0N (in_target[28]), .A1N (n_3), .B0 (n_31),
       .Y (n_60));
  OAI2BB1X1 g1661__4599(.A0N (in_target[29]), .A1N (n_3), .B0 (n_29),
       .Y (n_59));
  OAI2BB1X1 g1662__3779(.A0N (n_2), .A1N (n_69), .B0 (n_33), .Y (n_58));
  OAI2BB1X1 g1663__2007(.A0N (n_2), .A1N (n_94), .B0 (n_28), .Y (n_57));
  OAI2BB1X1 g1664__1237(.A0N (n_2), .A1N (n_70), .B0 (n_30), .Y (n_56));
  OAI2BB1X1 g1665__1297(.A0N (in_target[7]), .A1N (n_3), .B0 (n_26), .Y
       (n_55));
  OAI2BB1X1 g1666__2006(.A0N (in_target[31]), .A1N (n_3), .B0 (n_27),
       .Y (n_54));
  OAI2BB1X1 g1667__2833(.A0N (in_target[8]), .A1N (n_3), .B0 (n_25), .Y
       (n_53));
  OAI2BB1X1 g1668__7547(.A0N (in_target[9]), .A1N (n_3), .B0 (n_24), .Y
       (n_52));
  OAI2BB1X1 g1669__7765(.A0N (n_2), .A1N (n_75), .B0 (n_22), .Y (n_51));
  AOI22XL g1672__9867(.A0 (in_target[2]), .A1 (n_5), .B0 (n_2), .B1
       (n_1), .Y (n_50));
  OAI2BB1X1 g1673__3377(.A0N (in_target[14]), .A1N (n_3), .B0 (n_19),
       .Y (n_49));
  OAI2BB1X1 g1674__9719(.A0N (in_target[15]), .A1N (n_3), .B0 (n_18),
       .Y (n_48));
  OAI2BB1X1 g1675__1591(.A0N (n_2), .A1N (n_80), .B0 (n_17), .Y (n_47));
  OAI2BB1X1 g1676__6789(.A0N (in_target[17]), .A1N (n_3), .B0 (n_16),
       .Y (n_46));
  OAI2BB1X1 g1677__5927(.A0N (in_target[18]), .A1N (n_3), .B0 (n_15),
       .Y (n_45));
  OAI2BB1X1 g1678__2001(.A0N (n_2), .A1N (n_83), .B0 (n_14), .Y (n_44));
  OAI2BB1X1 g1679__1122(.A0N (in_target[20]), .A1N (n_3), .B0 (n_20),
       .Y (n_43));
  OAI2BB1X1 g1680__2005(.A0N (n_2), .A1N (n_85), .B0 (n_12), .Y (n_42));
  OAI2BB1X1 g1681__9771(.A0N (in_target[3]), .A1N (n_3), .B0 (n_10), .Y
       (n_41));
  OAI2BB1X1 g1682__3457(.A0N (in_target[22]), .A1N (n_3), .B0 (n_11),
       .Y (n_40));
  OAI2BB1X1 g1683__1279(.A0N (n_2), .A1N (n_87), .B0 (n_9), .Y (n_39));
  OAI2BB1X1 g1684__6179(.A0N (in_target[24]), .A1N (n_3), .B0 (n_8), .Y
       (n_38));
  OAI2BB1X1 g1685__7837(.A0N (in_target[4]), .A1N (n_3), .B0 (n_6), .Y
       (n_37));
  OAI2BB1X1 g1686__7557(.A0N (n_2), .A1N (n_89), .B0 (n_7), .Y (n_36));
  OAI2BB1X1 g1687__7654(.A0N (in_target[13]), .A1N (n_3), .B0 (n_13),
       .Y (n_35));
  AOI22XL g1688__8867(.A0 (n_2), .A1 (n_76), .B0 (in_stall), .B1
       (out_pc[12]), .Y (n_34));
  AOI22XL g1689__1377(.A0 (in_target[5]), .A1 (n_3), .B0 (in_stall),
       .B1 (out_pc[5]), .Y (n_33));
  AOI22XL g1690__3717(.A0 (in_target[27]), .A1 (n_3), .B0 (in_stall),
       .B1 (out_pc[27]), .Y (n_32));
  AOI22XL g1691__4599(.A0 (n_2), .A1 (n_92), .B0 (in_stall), .B1
       (out_pc[28]), .Y (n_31));
  AOI22XL g1692__3779(.A0 (in_target[6]), .A1 (n_3), .B0 (in_stall),
       .B1 (out_pc[6]), .Y (n_30));
  AOI22XL g1693__2007(.A0 (n_2), .A1 (n_93), .B0 (in_stall), .B1
       (out_pc[29]), .Y (n_29));
  AOI22XL g1694__1237(.A0 (in_target[30]), .A1 (n_3), .B0 (in_stall),
       .B1 (out_pc[30]), .Y (n_28));
  AOI22XL g1695__1297(.A0 (n_2), .A1 (n_95), .B0 (in_stall), .B1
       (out_pc[31]), .Y (n_27));
  AOI22XL g1696__2006(.A0 (n_2), .A1 (n_71), .B0 (in_stall), .B1
       (out_pc[7]), .Y (n_26));
  AOI22XL g1697__2833(.A0 (n_2), .A1 (n_72), .B0 (in_stall), .B1
       (out_pc[8]), .Y (n_25));
  AOI22XL g1698__7547(.A0 (n_2), .A1 (n_73), .B0 (in_stall), .B1
       (out_pc[9]), .Y (n_24));
  AOI22XL g1699__7765(.A0 (n_2), .A1 (n_74), .B0 (in_stall), .B1
       (out_pc[10]), .Y (n_23));
  AOI22XL g1700__9867(.A0 (in_target[11]), .A1 (n_3), .B0 (in_stall),
       .B1 (out_pc[11]), .Y (n_22));
  AOI22XL g1701__3377(.A0 (in_target[26]), .A1 (n_3), .B0 (in_stall),
       .B1 (out_pc[26]), .Y (n_21));
  AOI22XL g1702__9719(.A0 (n_2), .A1 (n_84), .B0 (in_stall), .B1
       (out_pc[20]), .Y (n_20));
  AOI22XL g1703__1591(.A0 (n_2), .A1 (n_78), .B0 (in_stall), .B1
       (out_pc[14]), .Y (n_19));
  AOI22XL g1704__6789(.A0 (n_2), .A1 (n_79), .B0 (in_stall), .B1
       (out_pc[15]), .Y (n_18));
  AOI22XL g1705__5927(.A0 (in_target[16]), .A1 (n_3), .B0 (in_stall),
       .B1 (out_pc[16]), .Y (n_17));
  AOI22XL g1706__2001(.A0 (n_2), .A1 (n_81), .B0 (in_stall), .B1
       (out_pc[17]), .Y (n_16));
  AOI22XL g1707__1122(.A0 (n_2), .A1 (n_82), .B0 (in_stall), .B1
       (out_pc[18]), .Y (n_15));
  AOI22XL g1708__2005(.A0 (in_target[19]), .A1 (n_3), .B0 (in_stall),
       .B1 (out_pc[19]), .Y (n_14));
  AOI22XL g1709__9771(.A0 (n_2), .A1 (n_77), .B0 (in_stall), .B1
       (out_pc[13]), .Y (n_13));
  AOI22XL g1710__3457(.A0 (in_target[21]), .A1 (n_3), .B0 (in_stall),
       .B1 (out_pc[21]), .Y (n_12));
  AOI22XL g1711__1279(.A0 (n_2), .A1 (n_86), .B0 (in_stall), .B1
       (out_pc[22]), .Y (n_11));
  AOI22XL g1712__6179(.A0 (n_2), .A1 (n_67), .B0 (in_stall), .B1
       (out_pc[3]), .Y (n_10));
  AOI22XL g1713__7837(.A0 (in_target[23]), .A1 (n_3), .B0 (in_stall),
       .B1 (out_pc[23]), .Y (n_9));
  AOI22XL g1714__7557(.A0 (n_2), .A1 (n_88), .B0 (in_stall), .B1
       (out_pc[24]), .Y (n_8));
  AOI22XL g1715__7654(.A0 (in_target[25]), .A1 (n_3), .B0 (in_stall),
       .B1 (out_pc[25]), .Y (n_7));
  AOI22XL g1716__8867(.A0 (n_2), .A1 (n_68), .B0 (in_stall), .B1
       (out_pc[4]), .Y (n_6));
  MX2X1 g1717__1377(.A (n_0), .B (in_transfert), .S0 (out_pc[2]), .Y
       (n_5));
  CLKINVX4 g1718(.A (n_4), .Y (n_3));
  NAND2XL g1719__3717(.A (in_transfert), .B (n_0), .Y (n_4));
  NOR2X2 g1720__4599(.A (in_transfert), .B (in_stall), .Y (n_2));
  INVX1 g1721(.A (out_pc[2]), .Y (n_1));
  INVX2 g1722(.A (in_stall), .Y (n_0));
  CLKXOR2X1 add_29_43_g200__3779(.A (out_pc[31]), .B (add_29_43_n_55),
       .Y (n_95));
  ADDHX1 add_29_43_g201__2007(.A (out_pc[30]), .B (add_29_43_n_53), .CO
       (add_29_43_n_55), .S (n_94));
  ADDHX1 add_29_43_g202__1237(.A (out_pc[29]), .B (add_29_43_n_51), .CO
       (add_29_43_n_53), .S (n_93));
  ADDHX1 add_29_43_g203__1297(.A (out_pc[28]), .B (add_29_43_n_49), .CO
       (add_29_43_n_51), .S (n_92));
  ADDHX1 add_29_43_g204__2006(.A (out_pc[27]), .B (add_29_43_n_47), .CO
       (add_29_43_n_49), .S (n_91));
  ADDHX1 add_29_43_g205__2833(.A (out_pc[26]), .B (add_29_43_n_45), .CO
       (add_29_43_n_47), .S (n_90));
  ADDHX1 add_29_43_g206__7547(.A (out_pc[25]), .B (add_29_43_n_43), .CO
       (add_29_43_n_45), .S (n_89));
  ADDHX1 add_29_43_g207__7765(.A (out_pc[24]), .B (add_29_43_n_41), .CO
       (add_29_43_n_43), .S (n_88));
  ADDHX1 add_29_43_g208__9867(.A (out_pc[23]), .B (add_29_43_n_39), .CO
       (add_29_43_n_41), .S (n_87));
  ADDHX1 add_29_43_g209__3377(.A (out_pc[22]), .B (add_29_43_n_37), .CO
       (add_29_43_n_39), .S (n_86));
  ADDHX1 add_29_43_g210__9719(.A (out_pc[21]), .B (add_29_43_n_35), .CO
       (add_29_43_n_37), .S (n_85));
  ADDHX1 add_29_43_g211__1591(.A (out_pc[20]), .B (add_29_43_n_33), .CO
       (add_29_43_n_35), .S (n_84));
  ADDHX1 add_29_43_g212__6789(.A (out_pc[19]), .B (add_29_43_n_31), .CO
       (add_29_43_n_33), .S (n_83));
  ADDHX1 add_29_43_g213__5927(.A (out_pc[18]), .B (add_29_43_n_29), .CO
       (add_29_43_n_31), .S (n_82));
  ADDHX1 add_29_43_g214__2001(.A (out_pc[17]), .B (add_29_43_n_27), .CO
       (add_29_43_n_29), .S (n_81));
  ADDHX1 add_29_43_g215__1122(.A (out_pc[16]), .B (add_29_43_n_25), .CO
       (add_29_43_n_27), .S (n_80));
  ADDHX1 add_29_43_g216__2005(.A (out_pc[15]), .B (add_29_43_n_23), .CO
       (add_29_43_n_25), .S (n_79));
  ADDHX1 add_29_43_g217__9771(.A (out_pc[14]), .B (add_29_43_n_21), .CO
       (add_29_43_n_23), .S (n_78));
  ADDHX1 add_29_43_g218__3457(.A (out_pc[13]), .B (add_29_43_n_19), .CO
       (add_29_43_n_21), .S (n_77));
  ADDHX1 add_29_43_g219__1279(.A (out_pc[12]), .B (add_29_43_n_17), .CO
       (add_29_43_n_19), .S (n_76));
  ADDHX1 add_29_43_g220__6179(.A (out_pc[11]), .B (add_29_43_n_15), .CO
       (add_29_43_n_17), .S (n_75));
  ADDHX1 add_29_43_g221__7837(.A (out_pc[10]), .B (add_29_43_n_13), .CO
       (add_29_43_n_15), .S (n_74));
  ADDHX1 add_29_43_g222__7557(.A (out_pc[9]), .B (add_29_43_n_11), .CO
       (add_29_43_n_13), .S (n_73));
  ADDHX1 add_29_43_g223__7654(.A (out_pc[8]), .B (add_29_43_n_9), .CO
       (add_29_43_n_11), .S (n_72));
  ADDHX1 add_29_43_g224__8867(.A (out_pc[7]), .B (add_29_43_n_7), .CO
       (add_29_43_n_9), .S (n_71));
  ADDHX1 add_29_43_g225__1377(.A (out_pc[6]), .B (add_29_43_n_5), .CO
       (add_29_43_n_7), .S (n_70));
  ADDHX1 add_29_43_g226__3717(.A (out_pc[5]), .B (add_29_43_n_3), .CO
       (add_29_43_n_5), .S (n_69));
  ADDHX1 add_29_43_g227__4599(.A (out_pc[4]), .B (add_29_43_n_1), .CO
       (add_29_43_n_3), .S (n_68));
  ADDHX1 add_29_43_g228__3779(.A (out_pc[3]), .B (out_pc[2]), .CO
       (add_29_43_n_1), .S (n_67));
endmodule

