tclmode

# Generated by Genus(TM) Synthesis Solution 17.10-p007_1, revision 1.191l
# Generated on: Tue Dec 11 01:01:00 EST 2018 (Tue Dec 11 06:01:00 GMT 2018)

tcl_set_command_name_echo on

set_log_file ./fv/rv_alu/rtl_to_fv_map.log -replace

usage -auto -elapse

set_verification_information ./rtl_fv_map_db

read_implementation_information fv/rv_alu -revised fv_map

set_parallel_option -threads 4 -license "xl lp gxl lpgxl eco ecogxl" -norelease_license

set env(RC_VERSION)     "17.10-p007_1"
set env(CDN_SYNTH_ROOT) "/CMC/tools/cadence/GENUS17.10.000_lnx86/tools.lnx86"
set CDN_SYNTH_ROOT      "/CMC/tools/cadence/GENUS17.10.000_lnx86/tools.lnx86"
set env(CW_DIR) "/CMC/tools/cadence/GENUS17.10.000_lnx86/tools.lnx86/lib/chipware"
set CW_DIR      "/CMC/tools/cadence/GENUS17.10.000_lnx86/tools.lnx86/lib/chipware"
# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both
add_search_path -library /CMC/kits/AMSKIT616_GPDK/tech/gsclib045/gsclib045/timing /CMC/kits/AMSKIT616_GPDK/tech/gsclib045/gsclib045/lef /CMC/kits/AMSKIT616_GPDK/tech/giolib045/giolib045/lef /CMC/kits/AMSKIT616_GPDK/tech/gsclib045/gsclib045/qrc/qx
read_library -liberty -both /CMC/kits/AMSKIT616_GPDK/tech/gsclib045/gsclib045/timing/fast_vdd1v0_basicCells.lib /CMC/kits/AMSKIT616_GPDK/tech/gsclib045/gsclib045/timing/fast_vdd1v0_multibitsDFF.lib /CMC/kits/AMSKIT616_GPDK/tech/gsclib045/gsclib045/timing/fast_vdd1v0_extvdd1v0.lib /CMC/kits/AMSKIT616_GPDK/tech/gsclib045/gsclib045/timing/fast_vdd1v0_basicCells.lib /CMC/kits/AMSKIT616_GPDK/tech/gsclib045/gsclib045/timing/fast_vdd1v0_multibitsDFF.lib /CMC/kits/AMSKIT616_GPDK/tech/gsclib045/gsclib045/timing/fast_vdd1v0_extvdd1v0.lib

set_naming_style rc
set_naming_rule "%s\[%d\]" -instance_array
set_naming_rule "%s_reg" -register -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -instance
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -variable
set_undriven_signal Z -golden
set_hdl_options -VERILOG_INCLUDE_DIR "incdir:sep:src:cwd"
delete_search_path -all -design -golden
add_search_path /users/Cours/ele8304/2/Labs/Lab2/sources/hdl -design -golden
read_design -rangeconstraint -configuration  -enumconstraint -golden -lastmod -noelab -vhdl 2008 /users/Cours/ele8304/2/Labs/Lab2/sources/hdl/pkg.vhd -vhdl 2008 /users/Cours/ele8304/2/Labs/Lab2/sources/hdl/hadd.vhd -vhdl 2008 /users/Cours/ele8304/2/Labs/Lab2/sources/hdl/adder.vhd -vhdl 2008 /users/Cours/ele8304/2/Labs/Lab2/sources/hdl/shifter.vhd -vhdl 2008 /users/Cours/ele8304/2/Labs/Lab2/sources/hdl/alu.vhd
elaborate_design -golden -root {rv_alu} -rootonly

read_design -verilog95  -revised -lastmod -noelab -unzip fv/rv_alu/fv_map.v.gz
elaborate_design -revised -root {rv_alu}

report_design_data
report_black_box
uniquify -all -nolib -golden
set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_analyze_option -auto

set_system_mode lec
analyze_datapath -module -verbose
analyze_datapath  -verbose
# report_mapped_points
report_unmapped_points -summary
report_unmapped_points -extra -unreachable -notmapped
add_compared_points -all
# report_compared_points
compare

# report_compare_data
report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_verification_information
report_verification_information

exit
